<?php

namespace App\Services\Sifak;

use App\Models\StoredFile;
use App\Models\TaDocumentVersion;
use App\Models\TugasAkhir;
use App\Services\Shared\Audit\AuditService;
use App\Services\Shared\Storage\TenantStorageService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;

class TaFinalizationService
{
    public function __construct(
        private readonly TaProgressService $progress,
        private readonly TenantStorageService $storage,
        private readonly AuditService $audit,
    ) {}

    public function checklist(TugasAkhir $ta): array
    {
        $readiness = $this->progress->readiness($ta);

        return [
            'judul' => filled($ta->judul),
            'pembimbing' => filled($ta->pembimbing_1_id),
            'required_sections_approved' => $readiness['pending_sections'] === [],
            'metadata' => filled($ta->program_studi_id) && filled($ta->mahasiswa_id),
            'unresolved_comments' => ! $ta->documents()->whereHas('currentVersion.comments', fn ($query) => $query->where('status', 'open'))->exists(),
        ];
    }

    public function finalize(TugasAkhir $ta): TugasAkhir
    {
        $checklist = $this->checklist($ta);

        if (in_array(false, $checklist, true)) {
            throw ValidationException::withMessages(['ta' => 'Finalisasi ditolak, checklist belum lengkap.']);
        }

        $ta->update(['status' => 'finalized']);
        $this->audit->record('TA_FINALIZATION_STARTED', 'M7', $ta, [], ['checklist' => $checklist]);

        return $this->compile($ta);
    }

    public function compile(TugasAkhir $ta): TugasAkhir
    {
        $firstDocument = $ta->documents()->orderBy('id')->first();

        if (! $firstDocument) {
            throw ValidationException::withMessages(['ta' => 'Finalisasi ditolak, belum ada dokumen TA.']);
        }

        $content = "Dokumen Final TA\n\nJudul: {$ta->judul}\nMahasiswa: {$ta->mahasiswa?->name}\nNIM: {$ta->mahasiswa?->nim}\n\nGenerated by SIFAK M7.";
        $relative = ($ta->mahasiswa?->nim ?? $ta->id) . '/final/thesis_final_' . now()->format('YmdHis') . '.txt';
        $path = $this->storage->put('ta', $relative, $content);
        $checksum = hash('sha256', $content);
        $versionNumber = ((int) $firstDocument->versions()->max('version_number')) + 1;

        $storedFile = StoredFile::create([
            'tenant_id' => $ta->tenant_id,
            'module' => 'ta',
            'owner_type' => TugasAkhir::class,
            'owner_id' => (string) $ta->id,
            'original_name' => 'thesis_final.txt',
            'stored_name' => basename($path),
            'disk' => config('filesystems.default'),
            'path' => $path,
            'mime_type' => 'text/plain',
            'size' => strlen($content),
            'checksum' => $checksum,
            'version' => 1,
            'status' => 'active',
            'uploaded_by' => Auth::id(),
        ]);

        $version = TaDocumentVersion::create([
            'tenant_id' => $ta->tenant_id,
            'ta_document_id' => $firstDocument->id,
            'version_number' => $versionNumber,
            'stored_file_id' => $storedFile->id,
            'submitted_by' => Auth::id(),
            'submitted_at' => now(),
            'change_summary' => 'Compiled final document placeholder',
            'status' => 'reviewed',
            'checksum' => $checksum,
        ]);

        $ta->update([
            'final_document_version_id' => $version->id,
            'status' => 'finalized',
            'progress_percent' => 100,
        ]);

        $this->audit->record('TA_FINAL_COMPILED', 'M7', $ta, [], ['stored_file_id' => $storedFile->id, 'checksum' => $checksum]);

        return $ta->fresh();
    }
}
