// Konten statis manual guide: kesesuaian dengan dokumen kebutuhan, temuan QA, dan deskripsi role.
// Status: OK = sesuai, PARTIAL = sebagian, NO = belum tersedia.

const conformity = {
  m1: [
    ['Pendaftaran Sempro & Sidang TA', 'OK', 'Jenis SEMPRO dan SIDANG_TA tersedia dengan alur yang sama.'],
    ['Persyaratan & validasi otomatis', 'OK', 'Syarat sistem (aktif, min. SKS, pembimbing, kesiapan dokumen M7) dicek otomatis saat daftar/submit.'],
    ['Kelengkapan berkas', 'PARTIAL', 'Verifikasi berkas manual via "Waive Manual"; belum ada menu unggah berkas syarat oleh mahasiswa.'],
    ['Verifikasi admin & minta perbaikan', 'OK', 'Aksi Verifikasi / Minta Perbaikan dengan catatan.'],
    ['Penetapan pembimbing & plotting penguji', 'OK', 'Peran Pembimbing 1/2, Penguji 1/2, Ketua, Sekretaris; pembimbing tidak boleh menjadi penguji.'],
    ['Rekomendasi penguji (M5) & cek beban', 'OK', 'Kandidat dengan skor kecocokan dan beban dosen.'],
    ['Cek availability & bentrok jadwal', 'OK', 'Bentrok ruang, penguji, mahasiswa, dan jadwal kuliah dosen (M4) — terbukti saat uji.'],
    ['Jadwal, ruangan, pelaksanaan (mulai/selesai)', 'OK', 'Finalisasi, Mulai, Selesai; jadwal ulang otomatis berstatus rescheduled.'],
    ['Penilaian rubrik berbobot & catatan', 'OK', 'Nilai per rubrik → rekap berbobot (contoh: 83.86 / B / Lulus).'],
    ['Keputusan, publikasi hasil', 'OK', 'Finalisasi Hasil + Publish.'],
    ['Revisi, deadline & validasi revisi', 'OK', 'Revisi oleh penguji, divalidasi setelah diperbaiki.'],
    ['Berita acara & dokumen hasil', 'PARTIAL', 'Berita acara tergenerate sebagai file teks; belum PDF bertanda tangan.'],
    ['Notifikasi', 'PARTIAL', 'Notifikasi in-app; email/WhatsApp belum (tahap lanjutan sesuai README).'],
    ['Dashboard monitoring & riwayat', 'OK', 'Beranda menampilkan pendaftaran perlu verifikasi, jadwal bentrok, dan agenda sidang per role.'],
    ['Audit log', 'OK', 'Setiap langkah tercatat di Audit Log.'],
  ],
  m2: [
    ['Jenis surat, template, form dinamis', 'OK', 'Form dinamis kini tampil otomatis per jenis surat (sebelumnya JSON manual — diperbaiki).'],
    ['Pengajuan & lampiran', 'OK', 'Data mahasiswa terisi otomatis.'],
    ['Verifikasi, approval berjenjang, revisi, tolak', 'OK', 'Admin Prodi → Kaprodi → Admin Fakultas.'],
    ['Penomoran otomatis', 'OK', 'Format 003/AKD/FASILKOM/X/2026 dari sequence.'],
    ['Document generation PDF/DOCX', 'PARTIAL', 'Dokumen dibuat dalam format HTML; PDF/DOCX final belum.'],
    ['QR / token verifikasi publik', 'OK', 'Halaman /verify/letter/{token} menampilkan "Surat Valid".'],
    ['Distribusi & arsip', 'OK', 'Status Terdistribusi → Arsip.'],
    ['Search, filter, history, audit', 'OK', 'Riwayat approval & audit tersedia.'],
    ['Notifikasi', 'PARTIAL', 'In-app saja.'],
    ['Laporan', 'PARTIAL', 'Permission export tersedia, belum ada menu laporan khusus.'],
  ],
  m3: [
    ['Monitoring KRS, SKS, IPK', 'OK', 'Rule KRS_NOT_FINAL, SKS_PROGRESS_GAP, IPK_LOW.'],
    ['Monitoring TA, Sempro, Sidang, Revisi', 'OK', 'Rule TA_PROGRESS_LOW, TA_INACTIVE, SEMESTER_WITHOUT_SEMPRO/SIDANG_TA, REVISION_OVERDUE.'],
    ['Monitoring CPL/PLO', 'OK', 'Rule CPL_PLO_GAP.'],
    ['Klasifikasi risiko hijau/kuning/merah', 'OK', 'Snapshot & alert menyimpan tingkat risiko.'],
    ['Alert, acknowledge, follow-up, eskalasi, resolve', 'OK', 'Diuji end-to-end lintas 4 role.'],
    ['Dashboard', 'OK', 'Ringkasan risiko di Beranda staf & pimpinan; alert baru di Beranda mahasiswa/Dosen PA.'],
    ['Trend', 'PARTIAL', 'Histori snapshot tersimpan; belum grafik tren.'],
    ['Scheduler', 'OK', 'evaluate-alerts terjadwal harian 03:00.'],
    ['Notifikasi & queue', 'PARTIAL', 'Notifikasi in-app.'],
    ['History & audit', 'OK', 'Follow-up, eskalasi, snapshot tercatat.'],
  ],
  m4: [
    ['Periode KRS', 'OK', 'Termasuk masa revisi. (Data seed periode sudah lewat — perlu diperpanjang.)'],
    ['Penawaran MK, hitung peminat, pembentukan kelas', 'OK', 'Aksi Hitung Peminat & Generate Kelas.'],
    ['Pengisian KRS', 'OK', 'Aksi "Tambah MK" dari penawaran (ditambahkan saat QA).'],
    ['Validasi SKS, prasyarat, kurikulum, periode', 'OK', 'Hasil per aturan di Krs Validation Results.'],
    ['Validasi bentrok jadwal mahasiswa', 'NO', 'Belum ada aturan bentrok jadwal antar-MK di validasi KRS.'],
    ['Approval Dosen PA, revisi, finalisasi', 'OK', 'Approve / Minta Revisi / Final.'],
    ['Rekomendasi dosen M5 & plotting', 'OK', 'Aksi "M5 Kandidat" pada kelas.'],
    ['Penjadwalan, alokasi ruang, cek konflik, riwayat', 'OK', 'Cek Konflik, Jadwal Conflicts, Jadwal Histories.'],
    ['Notifikasi', 'PARTIAL', 'Notifikasi in-app ke Dosen PA saat KRS diajukan.'],
    ['Dashboard akademik', 'OK', 'Beranda: status KRS mahasiswa, KRS menunggu Dosen PA, KRS siap difinalkan.'],
    ['Audit log', 'OK', 'KRS_CREATED / UPDATED / SUBMITTED tercatat.'],
  ],
  m5: [
    ['Profil, rumpun ilmu, KBK, keahlian', 'OK', ''],
    ['Pendidikan, sertifikasi, publikasi, pengalaman industri', 'OK', 'Dosen hanya bisa mengisi data miliknya (diperbaiki saat QA).'],
    ['Riwayat mengajar & preferensi MK', 'OK', 'Duplikat preferensi kini ditolak dengan pesan (sebelumnya error 500).'],
    ['Beban dosen & matriks kesesuaian', 'OK', ''],
    ['Rekomendasi pengampu (accept/reject)', 'OK', 'Hanya Admin Prodi/Kaprodi/KBK yang dapat memutuskan (diperbaiki).'],
    ['Rekomendasi pembimbing/penguji', 'OK', 'Dipakai oleh M1.'],
    ['Jadwal konsultasi & lokasi/ketersediaan', 'OK', 'Kini juga dapat dilihat mahasiswa (ditambahkan).'],
    ['Dashboard KBK & gap kompetensi dosen', 'PARTIAL', 'Beranda KBK menampilkan rekomendasi & sertifikasi menunggu; analitik gap dosen belum divisualkan.'],
    ['Histori rekomendasi & audit perubahan profil', 'OK', 'Recalculate harian 04:00.'],
  ],
  m6: [
    ['Profil akademik, IPK, SKS, riwayat KRS', 'OK', ''],
    ['CPL, PLO, profil lulusan & pemetaan', 'OK', 'Pemetaan MK–CPL & CPL–PLO.'],
    ['Minat, sertifikasi, portofolio, organisasi, MBKM', 'OK', 'Mahasiswa hanya mengisi data miliknya; verifikasi oleh staf (diperbaiki).'],
    ['Kekuatan & gap kompetensi', 'OK', 'Competency Gaps.'],
    ['Rekomendasi karier, topik TA, pembimbing, profil lulusan', 'OK', 'Dengan reason summary (explainability).'],
    ['Rekomendasi mata kuliah', 'NO', 'Tipe rekomendasi MK belum dihasilkan.'],
    ['Recommendation history', 'OK', ''],
    ['Dashboard mahasiswa & prodi', 'PARTIAL', 'Beranda menampilkan status & rekomendasi; grafik capaian CPL belum ada.'],
  ],
  m7: [
    ['Metadata TA, judul, pembimbing', 'OK', ''],
    ['Struktur dokumen per bab', 'OK', '8 bagian: Halaman Awal, Bab 1–5, Daftar Pustaka, Lampiran.'],
    ['Upload, versioning, review, revisi', 'OK', 'Versi 1 → revisi → versi 2 diuji.'],
    ['Approval bab & progres TA', 'OK', ''],
    ['Checklist & finalisasi', 'OK', ''],
    ['Compile dokumen final PDF/DOCX', 'PARTIAL', 'Dokumen final saat ini file teks hasil kompilasi; belum penggabungan PDF.'],
    ['Repositori, metadata, hak akses', 'OK', 'access_level & publish.'],
    ['Integrasi M1 (syarat sidang) & M3 (monitoring progres)', 'OK', ''],
    ['Notifikasi', 'PARTIAL', 'Notifikasi in-app ke pembimbing.'],
    ['Audit', 'OK', 'Ta Progress Logs & Audit Log.'],
  ],
};

const fixes = [
  ['Semua panel tenant', 'Asset JavaScript Filament dimuat dari domain pusat dan diblokir CORS di subdomain tenant (dropdown/tabel/upload bisa gagal).', 'ASSET_URL dikosongkan; image PHP dibangun ulang dengan entrypoint yang benar.', 'Kritis'],
  ['M7', 'Menu "Ta Document Versions" error 500 untuk Mahasiswa & Dosen (relasi salah pada scope akses).', 'Scope memakai relasi document.tugasAkhir.', 'Kritis'],
  ['M1', '"Finalisasi Hasil" selalu gagal jika nilai diinput lewat menu Sidang Scores (ringkasan penguji tidak pernah dibuat).', 'Ringkasan nilai berbobot dibuat saat nilai disubmit; finalisasi juga menghitungnya bila belum ada.', 'Kritis'],
  ['Semua modul', 'Pesan aturan bisnis (mis. "syarat belum lengkap", "jadwal bentrok") tidak tampil; tombol terlihat tidak berfungsi.', 'Pesan ditampilkan sebagai notifikasi merah di semua panel.', 'Tinggi'],
  ['M2', 'Aturan surat melempar RuntimeException → halaman error 500.', 'Diubah menjadi pesan validasi.', 'Tinggi'],
  ['Semua modul', 'Input data duplikat (unique key) → error 500.', 'Ditangani global menjadi notifikasi "Data sudah ada"; preferensi MK diberi validasi unik.', 'Tinggi'],
  ['M1 (keamanan)', 'Mahasiswa dapat mengubah status pendaftaran sidang sendiri (mis. langsung "verified").', 'Field status disembunyikan bagi mahasiswa.', 'Tinggi'],
  ['M2 (keamanan)', 'Pemohon dapat mengubah status surat menjadi APPROVED dan mengisi nomor surat sendiri.', 'Status/nomor/catatan hanya untuk staf berwenang.', 'Tinggi'],
  ['M4 (keamanan)', 'Mahasiswa dapat membuat KRS untuk mahasiswa lain, mengubah status ke final, serta mengisi nilai & grade sendiri di KRS Detail.', 'Field dikunci ke akun sendiri; status/nilai/validasi hanya untuk staf.', 'Kritis'],
  ['M5 (keamanan)', 'Dosen dapat mengisi data profil dosen lain, memvalidasi sertifikasi sendiri, dan menerima rekomendasi pengampu.', 'Data dikunci ke dosen login; validasi & accept/reject hanya untuk Admin Prodi/Kaprodi/KBK.', 'Tinggi'],
  ['M6 (keamanan)', 'Mahasiswa dapat mengisi data profil mahasiswa lain dan menandai sertifikasinya terverifikasi.', 'Data dikunci ke akun sendiri; verifikasi hanya staf.', 'Tinggi'],
  ['M1', 'Konflik jadwal tampil sebagai "[object Object]" dan form jadwal ulang tidak bisa disimpan.', 'Diganti ringkasan konflik yang mudah dibaca; status otomatis rescheduled.', 'Tinggi'],
  ['M2', 'Form pengajuan surat meminta data JSON mentah (spesifikasi: form dinamis).', 'Form dinamis dari Form Field Surat, data mahasiswa terisi otomatis.', 'Sedang'],
  ['M4', 'Tidak ada cara memilih mata kuliah dari penawaran saat mengisi KRS.', 'Aksi "Tambah MK" + validasi otomatis; pesan error menyebut aturan yang gagal.', 'Sedang'],
  ['M5', 'Jadwal konsultasi dosen tidak tersedia di panel Mahasiswa.', 'Menu ditambahkan (read-only).', 'Sedang'],
  ['M1/M7 (UX)', 'Semua tombol aksi tampil di setiap baris tanpa melihat status (tabel melebar, kolom NIM/nama tertutup).', 'Tombol tampil sesuai status.', 'Sedang'],
  ['Semua tabel (UX)', 'Data baru tampil di halaman terakhir.', 'Urutan default: terbaru di atas.', 'Rendah'],
  ['Semua panel (akses)', 'Menu tiap role berisi banyak fitur di luar tugasnya (mis. mahasiswa melihat Jenis Sidang, PLO, Kelas Kuliah; Kepala Lab melihat menu umum).', 'Menu & dashboard per role mengikuti dokumen aktor; halaman di luar fitur role ditolak (403) walau URL dibuka langsung.', 'Tinggi'],
  ['Semua panel (UX)', 'Beranda mahasiswa & dosen kosong; label menu bahasa Inggris otomatis ("Surats", "Krs", "Ta Documents"); tampilan antar panel berbeda.', 'Beranda baru per role (perlu tindakan, status, agenda, akses cepat), UI & label Bahasa Indonesia, tema seragam.', 'Sedang'],
  ['M4 (UX)', 'Menu M4 terpecah di dua grup ("KRS & Jadwal" dan "KRS & Penjadwalan").', 'Disatukan menjadi "M4 KRS & Penjadwalan".', 'Rendah'],
];

const openNotes = [
  ['Data seed', 'Periode KRS 2026-GANJIL berakhir 30 Sep 2026 sehingga KRS tidak dapat diajukan sampai periode diperpanjang Admin Prodi (dilakukan pada manual M4).'],
  ['M1/M2/M7', 'Berita acara, dokumen surat, dan dokumen final TA belum berupa PDF/DOCX resmi (masih teks/HTML).'],
  ['M4', 'Validasi bentrok jadwal antar-mata kuliah dalam satu KRS belum ada.'],
  ['M6', 'Rekomendasi mata kuliah belum dihasilkan (tipe lain sudah).'],
  ['Akses', 'Dosen yang menjadi pembimbing dapat melihat nilai dari penguji lain pada sidang bimbingannya — perlu konfirmasi kebijakan.'],
  ['Notifikasi', 'Email/WhatsApp, SSO, dan tanda tangan digital masih tahap lanjutan (sesuai README).'],
];

const roles = {
  superadmin: { desc: 'Level platform: mengelola tenant/fakultas, domain/subdomain, provisioning database tenant, user platform, dan audit. Tidak menjalankan proses akademik harian.', modules: 'Platform Multi-Tenant' },
  admin_fakultas: { desc: 'Operasional fakultas/TU: master data, surat menyurat end-to-end (nomor, generate, distribusi, arsip), dukungan sidang, monitoring, repositori TA.', modules: 'Master Data, M1, M2, M3, M7 (+ akses ke seluruh modul)' },
  admin_prodi: { desc: 'Akademik prodi: verifikasi syarat & plotting sidang, KRS & penjadwalan, verifikasi surat, rule monitoring, profiling dosen & mahasiswa, finalisasi TA.', modules: 'M1, M2 (verifikasi), M3, M4, M5, M6, M7' },
  dosen: { desc: 'Satu akun dosen memegang peran Dosen, Dosen PA, Pembimbing, dan Penguji: approval KRS, tindak lanjut alert, review & approval bab TA, penilaian & revisi sidang, profil dosen dan jadwal konsultasi.', modules: 'M1, M2 (pengajuan), M3, M4, M5, M6 (lihat), M7' },
  mahasiswa: { desc: 'Mengisi KRS, mengajukan surat, mendaftar sidang, menerima & acknowledge alert, melengkapi profil (minat/portofolio/MBKM), melihat rekomendasi, mengelola dokumen TA.', modules: 'M1, M2, M3, M4, M6, M7' },
  kaprodi: { desc: 'Pengawasan prodi: approval surat, monitoring & eskalasi alert, validasi rekomendasi pengampu, monitoring KRS, sidang, dan TA.', modules: 'M1, M2, M3, M4, M5, M6, M7' },
  dekan: { desc: 'Monitoring fakultas: surat strategis, dashboard risiko, peta beban & keahlian dosen, sebaran profil lulusan (read-only).', modules: 'M2, M3, M5, M6 (+ lihat M1, M4, M7)' },
  wd: { desc: 'Sama dengan Dekan untuk lingkup bidang akademik/kemahasiswaan (read-only).', modules: 'M2, M3, M5, M6' },
  kbk: { desc: 'Memvalidasi rumpun ilmu, keahlian dosen, matriks kesesuaian dosen–MK, dan menerima/menolak rekomendasi pengampu.', modules: 'M5' },
  lpm: { desc: 'Penjaminan mutu: memantau capaian CPL/PLO, profil lulusan, monitoring akademik, dan repositori TA (read-only).', modules: 'M1, M3, M6, M7 (read-only)' },
  baak: { desc: 'Rekap akademik: status sidang, monitoring kelulusan, rekap profil, dan repositori final untuk yudisium (read-only).', modules: 'M1, M3, M6, M7 (read-only)' },
  kalab: { desc: 'Melihat profil & riset dosen, mata kuliah, dan minat mahasiswa untuk kebutuhan laboratorium (read-only).', modules: 'M5 (read-only), Master Data' },
};

const keyActions = {
  admin_fakultas: ['Surat: Approve (acknowledgement), Nomor, Generate, Distribusi, Arsip', 'TA: Finalisasi, Buat Repository, Publish', 'Kelola jenis surat, form field, template, approval flow'],
  admin_prodi: ['Sidang: Validasi Syarat, Waive Manual, Verifikasi, Minta Perbaikan, Rekomendasi Penguji, Set Assignment, Finalisasi/Mulai/Selesai jadwal, Finalisasi Hasil, Publish, Berita Acara', 'Surat: Verifikasi, Minta Revisi, Tolak', 'KRS: Final; Penawaran: Hitung Peminat, Generate Kelas; Kelas: M5 Kandidat; Jadwal: Cek Konflik', 'Monitoring: Evaluasi alert; M6: Recalculate'],
  dosen: ['KRS: Approve / Minta Revisi (Dosen PA)', 'Alert: Tindak lanjut, Eskalasi', 'Sidang: input nilai rubrik + Submit, catat & validasi revisi (Penguji)', 'Dokumen TA: Minta Revisi, Approve (Pembimbing)', 'Isi pendidikan, sertifikasi, publikasi, preferensi MK, jadwal konsultasi'],
  mahasiswa: ['Sidang: daftar + Submit', 'Surat: ajukan (form dinamis) + Submit, Download', 'KRS: buat, Tambah MK, Validasi, Submit', 'Alert: Acknowledge', 'Profil: minat, sertifikasi, portofolio, organisasi, MBKM', 'Dokumen TA: Upload Versi, Submit'],
  kaprodi: ['Surat: Approve', 'Alert: Eskalasi, Resolve', 'Rekomendasi pengampu: Accept / Reject', 'Monitoring KRS, sidang, TA'],
  kbk: ['Mata Kuliah: Hitung rekomendasi', 'Rekomendasi pengampu: Accept / Reject', 'Kelola keahlian & matriks kesesuaian'],
};

module.exports = { conformity, fixes, openNotes, roles, keyActions };
